### ISSUE TITLE
Fix the Docker Stuff

### ISSUE THREAD

**Issue by jessehartloff** [makeopensource/devU#27]
Running docker compose up often gives a "can't find the generate-config.sh" file. It appears that this only occurs on Windows machines.. Look into this and find a solution where docker compose up just works the way it should. Always.

**Comment by RA341** [comment]
I might have figured out how to solve the config not found error

the solution is to convert your generateConfig.sh from CRLF(windows) to to LF which is how unix/macos separate their files.

If anyone has this problem try

Go to the generateConfig and look for the line seperator toggle and convert it to LF for your editor .

Webstorm has this toggle, vscode might have something similar. 

![image](https://github.com/makeopensource/devU/assets/39427910/c996c841-f058-4a35-8e18-8e406d13f5e5)

**Comment by epicseven-cup** [comment]
@y2nk4 and I fixed the config issue as there is a sync issue when you run docker compose, all the services are building at the same time which when you try to build the web service it does not find the default.yml file, though it works the second beacuse the config volume is being hooked to the config/ folder which will have the default.yml that was gerneated from the frist time.
