### ISSUE TITLE
Non-container grading endpoint

### ISSUE THREAD

**Issue by keiferms3** [makeopensource/devU#40]
Create an endpoint to run non-container autograders on a submission.

**Comment by RA341** [comment]
I talked to Jesse he said to import my grader function instead of a api endpoint.

Let me know what information you have available , when calling the grader i.e nonContainerAutograderID or assignment id so I can make the function accordingly

**Comment by keiferms3** [comment]
At the moment I'm retrieving all non-container autograders from the db that have the same assignmentId as the submission the endpoint has been called for. Then the submission's questions are iterated through, and for each question I check if a grader with a matching question exists, and if yes then perform the grading logic. I just pushed a commit with how the service function is at the moment if you want specifics.

So are you saying I should replace the grading logic with the grader's function? Or has the way we're handling grading changed as a whole and I should pivot what I'm doing to something else?

**Comment by RA341** [comment]
Prototype I came up with


```
export async function checkAnswer(studentAnswer: string, nonContainerAutoGrader: NonContainerAutoGrader) {
  /* eventual regex support
    if regex :
      if Regex(ncag.correctString).match(studentAnswer)
        return {nonContainerAutoGrader.question:nonContainerAutoGrader.score}
      else:
        return {nonContainerAutoGrader.question:0}
  */

  if (studentAnswer === nonContainerAutoGrader.correctString) {
    return nonContainerAutoGrader.score
  }
  return 0
}
```
